version: '3.8'

services:
  # Frontend React application
  taskpilot:
    build: .
    container_name: taskpilot-app
    ports:
      - "3030:80"
    restart: always
    environment:
      - NODE_ENV=production
      - REACT_APP_SUPABASE_URL=http://192.168.0.195:8000
      - REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY}

volumes:
  supabase-data: