version: '3.8'

services:
  # Frontend React application
  taskpilot:
    build: .
    container_name: taskpilot-app
    ports:
      - "80:80"
    restart: always
    environment:
      - NODE_ENV=production
      - REACT_APP_SUPABASE_URL=${SUPABASE_URL}
      - REACT_APP_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    depends_on:
      - supabase-db
      
  # Supabase database service
  supabase-db:
    image: supabase/postgres:15.1.0.37
    container_name: taskpilot-supabase
    restart: always
    volumes:
      - supabase-data:/var/lib/postgresql/data
      - ./supabase/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-taskpilot}
    ports:
      - "5432:5432"

volumes:
  supabase-data: