version: '3.8'

services:
  taskpilot:
    build: .
    container_name: taskpilot-app
    ports:
      - "3030:80"
    restart: always
    environment:
      - NODE_ENV=production
      - REACT_APP_SUPABASE_URL=http://192.168.0.195:8000
      - REACT_APP_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJyb2xlIjogImFub24iLAogICJpc3MiOiAic3VwYWJhc2UiLAogICJpYXQiOiAxNzQwNjEwODAwLAogICJleHAiOiAxODk4Mzc3MjAwCn0.A-NMpmKe_ORXXHpiBxJmJcMvlcL0STaJuyd708gotO8

volumes:
  supabase-data: