version: '3.8'

services:
  taskpilot:
    build: 
      context: .
      args:
        - REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
        - REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY}
    container_name: taskpilot-app
    ports:
      - "3030:80"
    restart: always